import type { NextPage } from 'next'
import Head from 'next/head'
import { ChangeEvent } from 'react';
import Script from 'next/script'

const Home: NextPage = () => {

  const onChange = (e: ChangeEvent<HTMLTextAreaElement>) => {
    // const newValue = e.target.value;
  }

  return (
    <div className="min-h-screen">
      <Head>
        <title>Notebook</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link  rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex/dist/katex.min.css" />
        <Script src="https://cdn.jsdelivr.net/npm/markdown-it/dist/markdown-it.min.js" />
      </Head>

      <main className="bg-slate-100 p-8 flex-1 flex flex-col">

        <h1 className="text-4xl mb-5">NoteBook</h1>
        <div className="grid grid-cols-2 gap-8">
          <div>
            <textarea className="min-w-full min-h-[70%]" onChange={onChange} value="テキストを入力"></textarea>
          </div>
          <div>
          <p>Hello</p>
          </div>
        </div>
      </main>

      <footer className="flex-1 flex px-8 border-t-[1] border-solid border-[#eaeaea] justify-center items-center">
        <a
          className="flex justify-center items-center grow"
          href="https://www.google.com/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '} CH-RANDOM
        </a>
      </footer>
    </div>
  )
}

export default Home
