import type { NextPage } from 'next'
import Head from 'next/head'
import { ChangeEvent } from 'react';
import Script from 'next/script'
import { Html, Main, NextScript } from 'next/document'

const Home: NextPage = () => {

  const onChange = (e: ChangeEvent<HTMLTextAreaElement>) => {
    // const newValue = e.target.value;
  }

  const tm = require('markdown-it-texmath');
  const md = require('markdown-it')({ html: true })
    .use(tm, {
      engine: require('katex'),
      delimiters: 'dollars',
      katexOptions: { macros: { "\\RR": "\\mathbb{R}" } }
    });
  const str = "Euler\'s identity $e^{i\\pi}+1=0$ is a beautiful formula in $\\RR^2$.";

  const data = md.render(str);

  return (
    <div className="min-h-screen">
      <Head>
        <title>Notebook</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <Script src="https://cdn.jsdelivr.net/npm/markdown-it/dist/markdown-it.min.js" />
        <Script src="https://cdn.jsdelivr.net/npm/katex/dist/katex.min.js" />
        <Script src="./texmath.js" />
      </Head>

      <main className="bg-slate-100 p-8 flex-1 flex flex-col">

        <h1 className="text-4xl mb-5">NoteBook</h1>
        <div className="grid grid-cols-2 gap-8">
          <div>
            <textarea className="min-w-full min-h-[70%]" onChange={onChange} value="テキストを入力"></textarea>
          </div>
          <div>
            <div id="notebook_preview_area" dangerouslySetInnerHTML={{ __html: data }} ></div>
          </div>
        </div>
      </main>

      <footer className="flex-1 flex px-8 border-t-[1] border-solid border-[#eaeaea] justify-center items-center">

        <p>Powered by {' '}<a
          href="https://ch-random.net/"
          target="_blank"
          rel="noopener noreferrer"
        >CH-RANDOM
        </a></p>
      </footer>
    </div>
  )
}

export default Home
