import type { NextPage } from 'next'
import Head from 'next/head'
import { ChangeEvent } from 'react';
import Script from 'next/script'
import { Html, Main, NextScript } from 'next/document'
import { useState } from "react";

const Home: NextPage = () => {

  const tm = require('markdown-it-texmath');
  const md = require('markdown-it')({ html: true })
    .use(tm, { delimiters: 'dollars' });

  const [previewHtmlData, setPreviewHtmlData] = useState("");

  const onTextChange = (e: ChangeEvent<HTMLTextAreaElement>) => {
    const newValue = e.target.value;
    console.log(md.render(newValue));
    setPreviewHtmlData(md.render(newValue));
  }

  return (
    <div className="min-h-screen">
      <Head>
        <title>Notebook</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <Script src="https://cdn.jsdelivr.net/npm/markdown-it/dist/markdown-it.min.js" />
        <Script src="https://cdn.jsdelivr.net/npm/katex/dist/katex.min.js" />
        <Script src="./texmath.js" />
      </Head>

      <main className="flex flex-col flex-1 p-8 bg-slate-100">

        <h1 className="mb-5 text-4xl">NoteBook</h1>
        <div className="grid grid-cols-2 gap-8">
          <div>
            <textarea name="notetext_area" className="min-w-full min-h-[70%]" onChange={onTextChange}></textarea>
          </div>
          <div>
            <div id="notebook_preview_area" dangerouslySetInnerHTML={{ __html: previewHtmlData }} ></div>
          </div>
        </div>
      </main>

      <footer className="flex-1 flex px-8 border-t-[1] border-solid border-[#eaeaea] justify-center items-center">

        <p>Powered by {' '}<a
          href="https://ch-random.net/"
          target="_blank"
          rel="noopener noreferrer"
        >CH-RANDOM
        </a></p>
      </footer>
    </div>
  )
}

export default Home
